const $=id=>document.getElementById(id);
const state={mode:localStorage.getItem("neetMode")||"objective",total:200,current:0,answers:[],marked:[],results:[],checkCurrent:0,remaining:12000,running:false,autoSave:true,timerEnabled:true,lastTick:Date.now(),filterMarked:false};
const answered=a=>state.mode==="objective"?a!==""&&a!=null:typeof a==="string"&&a.trim().length>0;
function fresh(n=200,seconds=12000){state.total=n;state.current=0;state.answers=state.mode==="objective"?Array(n).fill(null):Array(n).fill("");state.marked=Array(n).fill(false);state.results=Array(n).fill(null);state.checkCurrent=0;state.remaining=seconds;state.running=true;state.lastTick=Date.now()}
function save(){if(!state.autoSave)return;localStorage.setItem("neetMergedV3",JSON.stringify({...state,updated:Date.now()}))}
function load(){try{const x=JSON.parse(localStorage.getItem("neetMergedV3"));if(!x||!Array.isArray(x.answers))return false;Object.assign(state,x);state.lastTick=Date.now();return true}catch{return false}}
function clearSave(){localStorage.removeItem("neetMergedV3")}
function duration(){let h=Math.max(0,Math.min(23,+$("hoursInput").value||0)),m=Math.max(0,Math.min(59,+$("minutesInput").value||0)),s=Math.max(0,Math.min(59,+$("secondsInput").value||0));if(!h&&!m&&!s)m=20;return h*3600+m*60+s}
function setMode(mode){state.mode=mode;localStorage.setItem("neetMode",mode);document.querySelectorAll(".type-choice").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));$("modeLabel")&&($("modeLabel").textContent=mode==="objective"?"Objective / OMR":"Subjective")}
function answerValue(){return state.mode==="objective"?(document.querySelector(".omr.selected")?.dataset.opt||""):$("answerInput").value}
function syncInput(){if(state.mode==="objective"){const selected=document.querySelector(".omr.selected");state.answers[state.current]=selected?selected.dataset.opt:null}else state.answers[state.current]=$("answerInput").value;renderPalette();save()}
function buildAnswerUI(){const host=$("answerArea")||$("answerInput")?.parentElement?.parentElement;if(!host)return;
  if($("answerInput")&&state.mode==="subjective"){ $("answerInput").style.display=""; return}
  const options=document.querySelector(".omr-options"); if(options)options.style.display=state.mode==="objective"?"grid":"none";
  const subj=document.querySelector(".subjective-answer"); if(subj)subj.style.display=state.mode==="subjective"?"block":"none";
}
function selectObjective(opt){if(state.mode!=="objective")return;document.querySelectorAll(".omr").forEach(b=>b.classList.toggle("selected",b.dataset.opt===String(opt)));state.answers[state.current]=String(opt);renderPalette();save()}
function render(){const i=state.current,a=state.answers[i]??"";$("qNumber").textContent=i+1;$("qTotal").textContent=state.total;$("watermark").textContent=String(i+1).padStart(3,"0");const n=state.answers.filter(answered).length;$("answered").textContent=n;$("paletteSummary").textContent=`${n} / ${state.total} answered`;$("progress").style.width=(n/state.total*100)+"%";$("answerState").textContent=answered(a)?"ANSWERED":"UNANSWERED";$("answerState").classList.toggle("answered",answered(a));$("markBtn").textContent=state.marked[i]?"★ Marked for review":"☆ Mark for review";$("markBtn").classList.toggle("active",state.marked[i]);$("prevBtn").disabled=i===0;$("nextBtn").innerHTML=i===state.total-1?"Finish <span>✓</span>":"Next <span>→</span>";if(state.mode==="objective"){const opts=document.querySelector(".omr-options");if(opts)opts.style.display="grid";document.querySelectorAll(".omr").forEach(b=>b.classList.toggle("selected",String(b.dataset.opt)===String(a)));const sub=document.querySelector(".subjective-answer");if(sub)sub.style.display="none"}else{const opts=document.querySelector(".omr-options");if(opts)opts.style.display="none";const sub=document.querySelector(".subjective-answer");if(sub)sub.style.display="block";$("answerInput").value=a||"";$("charCount").textContent=`${(a||"").length} / 5000`}renderPalette();updateTimer()}
function renderPalette(){const p=$("palette");p.innerHTML="";state.answers.forEach((a,i)=>{if(state.filterMarked&&!state.marked[i])return;const b=document.createElement("button");b.className="p-btn";if(answered(a))b.classList.add("answered");if(state.marked[i])b.classList.add("marked");if(i===state.current)b.classList.add("current");b.textContent=i+1;b.onclick=()=>{syncInput();state.current=i;render();save();if(state.mode==="subjective")$("answerInput").focus()};p.appendChild(b)})}
function next(){syncInput();if(state.current<state.total-1){state.current++;render();save();if(state.mode==="subjective")$("answerInput").focus()}else showReview()}
function prev(){syncInput();if(state.current>0){state.current--;render();save();if(state.mode==="subjective")$("answerInput").focus()}}
function mark(){state.marked[state.current]=!state.marked[state.current];render();save()}
function showReview(){syncInput();state.running=false;renderReview();$("test").classList.add("hidden");$("review").classList.remove("hidden");save()}
function renderReview(){const n=state.answers.filter(answered).length,m=state.marked.filter(Boolean).length;$("reviewAnswered").textContent=n;$("rsAnswered").textContent=n;$("rsUnanswered").textContent=state.total-n;$("rsMarked").textContent=m;$("rsTime").textContent=formatTime(state.remaining);const g=$("reviewGrid");g.innerHTML="";state.answers.forEach((a,i)=>{const d=document.createElement("div");d.className="review-item"+(state.marked[i]?" marked":"");d.innerHTML=`<strong>Q${i+1}${state.marked[i]?" ★":""}</strong><span class="${answered(a)?"ans":""}">${answered(a)?"Answered":"Unanswered"}</span>`;d.onclick=()=>{state.current=i;state.running=true;$("review").classList.add("hidden");$("test").classList.remove("hidden");render();save();if(state.mode==="subjective")$("answerInput").focus()};g.appendChild(d)})}
function checks(){return state.answers.map((a,i)=>answered(a)?i:null).filter(i=>i!==null)}
function cpos(){const l=checks();return Math.max(0,l.indexOf(state.checkCurrent))}
function startChecking(){const l=checks();if(!l.length){toast("No attempted questions to check");showReview();return}state.running=false;state.checkCurrent=l[0];renderChecking();$("review").classList.add("hidden");$("checking").classList.remove("hidden");save()}
function renderChecking(){const l=checks();if(!l.length){showReview();return}if(!l.includes(state.checkCurrent))state.checkCurrent=l[0];const i=state.checkCurrent,a=state.answers[i],r=state.results[i],pos=cpos();$("checkQuestion").textContent=`Q${i+1} / ${state.total}`;$("checkSelected").textContent=state.mode==="objective"?`Selected answer: ${a}`:"Subjective answer:";$("checkWatermark").textContent=String(i+1).padStart(3,"0");$("typedAnswerPreview").textContent=state.mode==="objective"?`Option ${a}`:a;$("checkResult").textContent=r==="correct"?"CORRECT":r==="incorrect"?"INCORRECT":"NOT CHECKED";$("checkResult").className="check-state "+(r||"");document.querySelectorAll(".result-btn").forEach(b=>b.classList.remove("active"));if(r==="correct")$("correctBtn").classList.add("active");if(r==="incorrect")$("incorrectBtn").classList.add("active");$("checkPrev").disabled=pos===0;$("checkedCount").textContent=l.filter(q=>state.results[q]).length;$("checkNext").innerHTML=pos===l.length-1?"Finish <span>✓</span>":"Next <span>→</span>";$("checkingSummary").textContent=`${l.filter(q=>state.results[q]).length} of ${l.length} attempted questions checked • ${state.results.filter(x=>x==="correct").length} correct • ${state.results.filter(x=>x==="incorrect").length} incorrect`}
function setResult(r){if(state.checkCurrent>=0&&answered(state.answers[state.checkCurrent])){state.results[state.checkCurrent]=r;renderChecking();save()}}
function checkNext(){const l=checks(),p=cpos();if(p<l.length-1){state.checkCurrent=l[p+1];renderChecking();save()}else finishChecking()}
function checkPrev(){const l=checks(),p=cpos();if(p>0){state.checkCurrent=l[p-1];renderChecking();save()}}
function finishChecking(){state.running=false;renderResults();$("checking").classList.add("hidden");$("results").classList.remove("hidden");save()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function renderResults(){const c=state.results.filter(x=>x==="correct").length,inc=state.results.filter(x=>x==="incorrect").length,n=state.answers.filter(answered).length,m=state.marked.filter(Boolean).length;$("scoreText").textContent=`${c} / ${state.total}`;$("accuracyText").textContent=`${state.total?((c/state.total)*100).toFixed(1):0}% accuracy`;$("finalCorrect").textContent=c;$("finalIncorrect").textContent=inc;$("finalUnattempted").textContent=state.total-n;$("finalMarked").textContent=m;const g=$("resultGrid");g.innerHTML="";state.answers.forEach((a,i)=>{const r=state.results[i],d=document.createElement("div");d.className="result-item "+(r||"");d.innerHTML=`<span class="result-label">Q${i+1} • ${r?r.toUpperCase():"NOT CHECKED"}</span><span class="result-answer">${answered(a)?esc(state.mode==="objective"?"Option "+a:String(a).slice(0,160)):"Unanswered"}</span>`;g.appendChild(d)})}
function formatTime(s){s=Math.max(0,Math.floor(s));return[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")}
function updateTimer(){$("timer").textContent=formatTime(state.remaining);$("rsTime").textContent=formatTime(state.remaining)}
function tick(){if(!state.running||!state.timerEnabled)return;const now=Date.now(),d=Math.floor((now-state.lastTick)/1000);if(d>0){state.remaining=Math.max(0,state.remaining-d);state.lastTick=now;updateTimer();save();if(!state.remaining){state.running=false;toast("Time is up — review your answer sheet");showReview()}}}
setInterval(tick,500)
function exportPDF(){const c=state.results.filter(x=>x==="correct").length,inc=state.results.filter(x=>x==="incorrect").length,n=state.answers.filter(answered).length,acc=state.total?((c/state.total)*100).toFixed(1):"0.0";const rows=state.answers.map((a,i)=>`<tr><td>${i+1}</td><td>${esc(state.mode==="objective"?(a?("Option "+a):"—"):(a||"—"))}</td><td>${state.marked[i]?"Yes":"No"}</td><td class="${state.results[i]||""}">${state.results[i]||"Not checked"}</td></tr>`).join("");const w=window.open("","_blank");if(!w){toast("Please allow pop-ups to export PDF");return}w.document.write(`<!doctype html><html><head><title>NEET ${state.mode==="objective"?"Objective":"Subjective"} Answer Sheet</title><style>body{font-family:Arial;padding:28px;color:#111}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #ddd;padding:6px;vertical-align:top;white-space:pre-wrap;word-break:break-word}th{background:#f1f3f5}.correct{color:#087f5b;font-weight:bold}.incorrect{color:#c92a2a;font-weight:bold}</style></head><body><h1>NEET ${state.mode==="objective"?"Objective / OMR":"Subjective"} Answer Sheet</h1><p>Total: ${state.total} &nbsp; Attempted: ${n} &nbsp; Correct: ${c} &nbsp; Incorrect: ${inc} &nbsp; Accuracy: ${acc}%</p><table><thead><tr><th>Question</th><th>${state.mode==="objective"?"Selected Answer":"Typed Answer"}</th><th>Marked</th><th>Result</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close();toast("PDF print dialog opened")}
function newPractice(){state.running=false;clearSave();$("review").classList.add("hidden");$("test").classList.add("hidden");$("checking").classList.add("hidden");$("results").classList.add("hidden");$("setup").classList.remove("hidden");setMode(state.mode)}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("neetTheme",document.body.classList.contains("dark")?"dark":"light");$("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"}
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.x);toast.x=setTimeout(()=>t.classList.remove("show"),1500)}
document.querySelectorAll(".type-choice").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));setMode(state.mode);
$("startBtn").onclick=()=>{fresh(Math.max(1,Math.min(200,+$("countInput").value||200)),duration());state.timerEnabled=$("timerToggle").checked;state.autoSave=$("autosaveToggle").checked;$("setup").classList.add("hidden");$("test").classList.remove("hidden");$("review").classList.add("hidden");$("checking").classList.add("hidden");$("results").classList.add("hidden");render();save();if(state.mode==="subjective")$("answerInput").focus()};
$("newBtn").onclick=newPractice;$("prevBtn").onclick=prev;$("nextBtn").onclick=next;$("markBtn").onclick=mark;$("reviewBtn").onclick=showReview;$("backBtn").onclick=()=>{state.running=true;state.lastTick=Date.now();$("review").classList.add("hidden");$("test").classList.remove("hidden");render();save();if(state.mode==="subjective")$("answerInput").focus()};$("checkBtn").onclick=startChecking;$("correctBtn").onclick=()=>setResult("correct");$("incorrectBtn").onclick=()=>setResult("incorrect");$("checkPrev").onclick=checkPrev;$("checkNext").onclick=checkNext;$("exportBtn").onclick=exportPDF;$("resultExportBtn").onclick=exportPDF;$("newPracticeBtn").onclick=newPractice;$("resultNewBtn").onclick=newPractice;$("themeBtn").onclick=toggleTheme;
document.addEventListener("click",e=>{const b=e.target.closest(".omr");if(b){e.preventDefault();selectObjective(b.dataset.opt)}});
$("answerInput")?.addEventListener("input",()=>{if(state.mode==="subjective"){state.answers[state.current]=$("answerInput").value;$("charCount").textContent=`${$("answerInput").value.length} / 5000`;renderPalette();save()}});
$("answerInput")?.addEventListener("keydown",e=>{if(state.mode==="subjective"&&e.key==="Enter"&&!e.shiftKey){e.preventDefault();next()}});
document.querySelectorAll(".step").forEach(b=>b.onclick=()=>{$("countInput").value=Math.max(1,Math.min(200,(+$("countInput").value||200)+(+b.dataset.step)))});
$("paletteMarkFilter").onclick=()=>{state.filterMarked=!state.filterMarked;$("paletteMarkFilter").classList.toggle("active",state.filterMarked);renderPalette()};$("countInput").onkeydown=e=>{if(e.key==="Enter")$("startBtn").click()};
document.addEventListener("keydown",e=>{if(e.target.tagName==="INPUT"||e.target.tagName==="TEXTAREA")return;if(!$("test").classList.contains("hidden")){if(e.key.toLowerCase()==="m"){e.preventDefault();mark()}else if(e.key==="Enter"){e.preventDefault();next()}else if(e.key==="ArrowRight"){e.preventDefault();next()}else if(e.key==="ArrowLeft"){e.preventDefault();prev()}else if(e.key==="Escape"){e.preventDefault();showReview()}else if(state.mode==="objective"&&["1","2","3","4"].includes(e.key)){e.preventDefault();selectObjective(e.key)}}else if(!$("checking").classList.contains("hidden")){if(e.key==="1"){e.preventDefault();setResult("correct")}else if(e.key==="2"){e.preventDefault();setResult("incorrect")}else if(e.key==="Enter"){e.preventDefault();checkNext()}else if(e.key==="ArrowRight"){e.preventDefault();checkNext()}else if(e.key==="ArrowLeft"){e.preventDefault();checkPrev()}else if(e.key==="Escape"){e.preventDefault();finishChecking()}}});
if(localStorage.getItem("neetTheme")==="dark"){document.body.classList.add("dark");$("themeBtn").textContent="☀"}$("timerToggle").checked=true;$("autosaveToggle").checked=true;
if(load()){$("countInput").value=state.total;let s=Math.max(0,state.remaining);$("hoursInput").value=Math.floor(s/3600);$("minutesInput").value=Math.floor(s%3600/60);$("secondsInput").value=s%60;$("timerToggle").checked=state.timerEnabled;$("autosaveToggle").checked=state.autoSave;$("setup").classList.add("hidden");$("test").classList.remove("hidden");render()}
